// Next
import type { Metadata } from "next";
import {
  NextIntlClientProvider,
  useMessages,
  useTranslations,
} from "next-intl";

// Components
import Layout from "@/components/layout/layout";

// Styles
import "@styles/base.css";
import Link from "next/link";

// SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <Layout>{children}</Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
